spring.application.name=duoprojectv1

spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/ihwa46
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=ihwauser
spring.datasource.password=ihwa123!

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

logging.level.org.mybatis=DEBUG
logging.level.java.sql=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.wecompany.duoprojectv1.domain


